### PR TITLE
Add functionality in mp/mps/mpo and add ExpDVR basis

### PR DESCRIPTION
**Pull request by jjren**
1. support the addition of many mpos/mpss together.
   `mps.add([mps1, mps2,....])`
2.  convertion between diagonal mpo and mps. 
   `Mpo.from_mps()`  `Mps.from_mpo()`
3. ExpDVR basis
4. add shift algorithm for excited states calculation ($H=H_0 + \sum_i \alpha_i |\psi_i><\psi_i|$).

### CODE REVIEW

**Review by atxy-blip — APPROVED** [review]
Looks good to me : )

**Comment by liwt31** [comment]
The test coverage is too low currently - it seems easy to add a few tests for these new functions

**Comment by jjren** [comment]
I will add doc and tests later.

**Comment by jjren** [comment]
I close the PR now and will open it again when the new features for nuclear dynamics are ready.

**Pull request closed without merging**
