### PR TITLE
modify imaginary time evolution for emission calculation

### PR DESCRIPTION
**Pull request by jiangtong1000**
- modify imaginary time evolution for emission calculation, can dump density matrix for further analysis #53

### CODE REVIEW

**Comment by liwt31** [comment]
This is a clever implementation but could be improved in several ways:
- It seems `period` function does not support scheme 4. Actually in scheme 4 where all electronic DOF is in the same site a much different approach should be used for periodic boundary condition MPO.
- If scheme 4 is taken into consideration, it'll be natural to make `period` an option of `Mpo`. Another reason for this is that other calculations may need to run in periodic conditions either.
- Adding some tests about the validity of the MPO should be nice.

Also a side note: it is not necessary to use `super()` for subclass methods every time. Do this only when the subclass has overwritten the ancestor's method and the overwritten method is desired.

**Comment by jiangtong1000** [comment]
> This is a clever implementation but could be improved in several ways:
> 
> * It seems `period` function does not support scheme 4. Actually in scheme 4 where all electronic DOF is in the same site a much different approach should be used for periodic boundary condition MPO.
> * If scheme 4 is taken into consideration, it'll be natural to make `period` an option of `Mpo`. Another reason for this is that other calculations may need to run in periodic conditions either.
> * Adding some tests about the validity of the MPO should be nice.
> 
> Also a side note: it is not necessary to use `super()` for subclass methods every time. Do this only when the subclass has overwritten the ancestor's method and the overwritten method is desired.

OK, I will come back later after I understand scheme 4, and for now maybe jiajun @jjren  will do some tests for the new constructed function.

**Comment by jjren** [comment]
I will write a more general MPO with periodic boundary condition. @jiangtong1000 @liwt31

**Comment by liwt31** [comment]
> I will write a more general MPO with periodic boundary condition.

My suggestion is to set `periodic` as an attribute of `MolList` and construct MPO accordingly.

**Pull request merged**
